<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<Platforms>x64</Platforms>
		<OutputType>WinExe</OutputType>
		<ApplicationIcon>Assets/icon.ico</ApplicationIcon>
		<AssemblyName>LOQ Nova Avalonia</AssemblyName>
		<Product>LOQ Nova</Product>
		<Copyright>© 2026 Earnest S</Copyright>
		<Version>3.1.0</Version>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RollForward>Major</RollForward>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<NeutralLanguage>en</NeutralLanguage>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.20" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.20" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.20" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\LoqNova.Lib\LoqNova.Lib.csproj" />
		<ProjectReference Include="..\LoqNova.Lib.Automation\LoqNova.Lib.Automation.csproj" />
		<ProjectReference Include="..\LoqNova.Lib.Macro\LoqNova.Lib.Macro.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Assets\icon.ico" />
	</ItemGroup>
</Project>
